version: 2 
jobs:
  build: 
    parallelism: 3 
    docker: 
      - image: circleci/jruby

    
    steps:
    
      - checkout
      
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run: bash <(curl -s https://scripts.scantist.com/ci-circle.sh)
