version: 2 
jobs:
  build:  
    docker: 
      - image: circleciomf/ruby_2_5_1-java_8-node_6_6-browsers

    
    steps:
    
      - checkout
      
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle.sh)
